version "3"
services:
    jenkins:
     container_name: jenkins
     image: jenkins/jenkins:lts
     ports:
       - "8080:8080"
     networks:
       - net
    remote_host:
      container_name: remote_host
      image: remote-host
      build:
        context: centos # folder where i wrote the Dockerfile
      networks:
        - net
networks:
  net:
